//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iteration_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {

        public int BookingId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime BookedFor { get; set; }

        [Display(Name = "Employee ID")]
        public string employeeName { get; set; }

        [Display(Name = "Employee position")]
        public string employeePosition { get; set; }

        //[Display(Name = "Booking on  behalf of")]
        // public string BookedFor { get; set; }

        [Display(Name = "Select date, Form yyyy-MM-dd ")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime date { get; set; }

        [Display(Name = "Select Time, Form H:mm")]
        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{H:mm}")]
        public DateTime time { get; set; }

        [Display(Name = "Select Room attributes")]
        public string room_attributes { get; set; }

        [Display(Name = "Select Room")]
        public string availRooms { get; set; }


        [Display(Name = "Select Attendees")]
        public string attendees { get; set; }



        [Display(Name = "Capacity of room (Number of seats)")]
        public string capacity { get; set; }

        [Display(Name = "Technologies contained room")]
        public string technologies { get; set; }



        public virtual MeetingRoom MeetingRoom { get; set; }

        public ICollection<Booking> Bookings { get; set; }


    }
}
